### ISSUE TITLE
 nebula-bench 报错

### ISSUE THREAD

**Issue by sunlc210** [vesoft-inc/nebula-bench#19]
运行 python3 run.py data  ，
会报如下错误

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/xml/serializer/TreeWalker
        at org.apache.xalan.processor.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:823)
        at org.apache.hadoop.conf.Configuration.writeXml(Configuration.java:3496)
        at org.apache.hadoop.conf.Configuration.writeXml(Configuration.java:3461)
        at org.apache.hadoop.conf.Configuration.writeXml(Configuration.java:3457)
        at org.apache.hadoop.mapreduce.JobSubmitter.writeConf(JobSubmitter.java:290)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:245)
        at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1570)
        at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1567)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)

能帮忙看一下吗

**Comment by sunlc210** [comment]
已经解决
